### PR TITLE
add cxs.prefix to config class prefix

### PR DESCRIPTION
**Pull request by aaronyo**
As discussed in issue #83.

### CODE REVIEW

**Comment by lawrencesong** [comment]
@aaronyo Do you want to make it consistent with monolithic as it's a function in there: `module.exports.prefix = val => prefix = val`

**Comment by lachlanjc** [comment]
Looks good. Small thing—run Prettier on these changes 😀

**Comment by Jascha-Sundaresan** [comment]
I agree w/ @lawrencesong and would like to see this mirror monolithic.js

**Comment by aaronyo** [comment]
I'm happy to change the PR to be like monolithic.js, @lawrencesong. What's the purpose of monolithic.js? I don't have time to investigate just now -- took a quick peek and wasn't obvious.

Also, I'll run prettier, @lachlanjc, though it is too bad a specific version of prettier isn't pegged in dev dependencies. I'll just go with the latest version.

-aaron

**Comment by lawrencesong** [comment]
@aaronyo I don't know what's the purpose of monolithic.js as I don't use it. I think it might be good to keep it consistent. It's not important to me for my use case.  It would be great to merge this ASAP so I can get rid of my local hack. Thanks for creating this pull request.

**Comment by aaronyo** [comment]
I changed cxs.prefix to a function to keep it consistent with monolithic.js.

Regarding running prettier: I did a rebase from master, and then I tried using prettier (latest version: 1.7.4). This led to numerous changes across the code base, so I didn't keep those changes. Instead, I just removed trailing semi-colons from my code, which was the only thing that I noticed was out of sync with the rest of the cxs project's code style.

I think prettier should be added to the projects package.json devDependencies so that all contributors can use the same version. I'll log an issue for that.

**Comment by aaronyo** [comment]
@lawrenceson, I'm not sure what the process here is for merging, but I'm not one of the project's maintainers and do not have permission to do that.

@lachlanjc, FYI: seem my comments about regarding running prettier.

**Comment by lachlanjc** [comment]
@aaronyo We could, or just run the latest version on PRs (with single quotes and no semicolons).

**Comment by aaronyo** [comment]
@lachlanjc In this case, that would have led to numerous changes unrelated to the feature I was adding. Several other pieces of code seemed to not be up to date.

You don't want to make patches confusing by including changes to unrelated pieces of code.

In my experience, the best solution is to have someone periodically update the projects prettier.js version, and then create a commit for the changes that happen across the code base.

**Comment by lawrencesong** [comment]
@lachlanjc any chance of merging this?

**Comment by lachlanjc** [comment]
@lawrencesong I can’t merge this, it’s @jxnblk’s project

**Comment by lawrencesong** [comment]
@jxnblk Is it possible to merge it or any change need to make? I think a few of us are waiting for this change.

**Comment by jxnblk** [comment]
Thanks for this and sorry for the delay! 😬

**Pull request merged**
